Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          DIU.Neos.AnchorLink:
            - Main
    Ui:
      resources:
        javascript:
          "DIU.Neos.AnchorLink":
            resource: '${"resource://DIU.Neos.AnchorLink/Public/JavaScript/AnchorLink/Plugin.js"}'
      frontendConfiguration:
        "Diu.Neos.AnchorLink":
          displaySearchBox: true
          threshold: 0
  Flow:
    security:
      authentication:
        providers:
          "Neos.Neos:Backend":
            requestPatterns:
              "DIU.Neos.AnchorLink:Backend":
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'DIU\Neos\AnchorLink\Controller\.*'
    mvc:
      routes:
        "DIU.Neos.AnchorLink":
          position: "before Neos.Neos"
DIU:
  Neos:
    AnchorLink:
      contentNodeType: "Neos.Neos:Content"
      anchor: ${node.properties.anchor || node.name}
      label: ${node.label}
      eelContext:
        String: Neos\Eel\Helper\StringHelper
        Array: Neos\Eel\Helper\ArrayHelper
        Date: Neos\Eel\Helper\DateHelper
        Configuration: Neos\Eel\Helper\ConfigurationHelper
        Math: Neos\Eel\Helper\MathHelper
        Json: Neos\Eel\Helper\JsonHelper
        I18n: Neos\Flow\I18n\EelHelper\TranslationHelper
        q: Neos\Eel\FlowQuery\FlowQuery::q
