Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          DIU.Neos.AnchorLink:
            - Main
    Ui:
      resources:
        javascript:
          "DIU.Neos.AnchorLink":
            resource: '${"resource://DIU.Neos.AnchorLink/Public/JavaScript/AnchorLink/Plugin.js"}'
      frontendConfiguration:
        "Diu.Neos.AnchorLink":
          displaySearchBox: true
          threshold: 0
  Flow:
    security:
      authentication:
        providers:
          "Neos.Neos:Backend":
            requestPatterns:
              "DIU.Neos.AnchorLink:Backend":
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'DIU\Neos\AnchorLink\Controller\.*'
    mvc:
      routes:
        "DIU.Neos.AnchorLink":
          position: "before Neos.Neos"
